### ISSUE TITLE
Refreshing the page loads a empty GeoGebra app

### ISSUE THREAD

**Issue by saunAAA** [saunAAA/react-geogebra#1]
The state of the embedded app is not stored. Refreshing the page loads a new empty GeoGebra app.
Idea: 
- save the current app before refreshing as a base64 encoded .ggb file in localstorage and load that file after refresh.

**Comment by Siignature** [comment]
`function loadGeogebraApp() {
        const parameter = JSON.parse(JSON.stringify(props));
        parameter.appletOnLoad = onLoad;
        const ggbApp = new window.GGBApplet(parameter, true);
        ggbApp.inject(id);
    }`

It seems the on load event listener is never triggered, so it never injects the ggbApp. I made it work puting it directly in the loadGeogebraApp.

**Comment by saunAAA** [comment]
Thanks for your participation.
The problem i'm talking about in this issue is, that a new applet with the given props is loaded after refreshing the page. 

The onLoad function in index.js is just a placeholder. The idea is, that you can reference to a specific function with the prop "appletOnLoad" and this function gets called in the onLoad function. If you not reference a function to  <Geogebra/> nothing will happen.

**Comment by saunAAA** [comment]
With Version 1.1.0 this issue is fixed. The current construction is stored in the sessionStorage. If the sessionStorage is not empty the construction is loaded from the sessionStorage.

**Comment by saunAAA** [comment]
with version 1.1.1 this behaviour is back
