### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by pmirla** [saunAAA/react-geogebra#2]
Could you please have a look, what is wrong here. 
This is example from your repo

[CodeSandBox Link](https://codesandbox.io/s/gifted-resonance-fl22n?file=/src/App.js
)
Thank you

**Comment by saunAAA** [comment]
Hello pmirla,

i don't really know how SandBow exactly works. I'm pretty sure it's a timing problem. The GeoGebra Applet gets injected before the javascript from "https://geogebra.org/apps/deployggb.js" is loaded.
If you want to use the component in SandBox you can inject the GGB by hand.
for example overwrite the "onChivron" Function like so:

  function onChivron() {
    //window.history.back();
    window.GGBApplet(
      {
        id: "appId",
        appName: "graphing",
        material_id: "xu9j3sgq",
        width: 600,
        height: 400,
        enableUndoRedo: false,
        appletOnLoad: registerGeogebraListeners
      },
      true
    ).inject("appId")
  }

I hope this helps. I'm not a professional. You can look in src/loadScript.js how the GeoGebra script-tag is injected. And in src/index how the GGBApplet is injected.

**Comment by pmirla** [comment]
Hello saunAAA,
Thanks very much for the suggestion. It worked.
I made the changes you proposed. 
Kind Regards
