### ISSUE TITLE
Handling fullscreen

### ISSUE THREAD

**Issue by Siignature** [saunAAA/react-geogebra#4]
Hello, first of all thanks for your great work.

Do you think there is some way to handle fullscreen (using for example react-full-screen), making the Geogebra adapt to the fullscreen without forcing a re-render and keeping the Geogebra current state?

The only way I made the Geogebra adapt to fullscreen whas forcing re-render changing the key when fullscreen but then I lose the Geogebra state.

Thanks in advance.

**Comment by saunAAA** [comment]
Hello,
please excuse my not so good english. There is a showFullscreenButton prop included in GeoGebra.
Pressing this button doesn't force a rerender in the current react-geogebra version.

**Comment by Siignature** [comment]
Hello, thanks for your fast reply.

That's true, but in my case, I want to handle fullscreen with external buttons, and it doesn't exist any javascript method in the Geogebra API to do it.

**Comment by saunAAA** [comment]
[https://help.geogebra.org/topic/javascript-api-command-to-set-fullscreen-mode](https://help.geogebra.org/topic/javascript-api-command-to-set-fullscreen-mode) according to this thread. it is not possible to trigger a fullscreen via JS API. Propably you could store the state in a base64 string and after re-render load the applet based from this base64 string.
